addons:
  homebrew:
    update: true
    brewfile: true
language: generic
matrix:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode11.2
    - os: osx
      osx_image: xcode10.3
    #- os: osx
    #  osx_image: xcode9.4  # brew update is excruciatingly slow on xcode9.4
script:
  - ./test/run.sh
